### ISSUE TITLE
open to boost license instead?

### ISSUE THREAD

**Issue by adamdruppe** [Inochi2D/objective-d#1]
bsd is incompatible with the D stdlib, but boost means it could have equal footing to windows and linux api bindings.

**Comment by LunaTheFoxgirl** [comment]
Yeah, could switch it over to boost license. Just went with BSD initially since that's what the rest of Inochi2D uses

**Comment by adamdruppe** [comment]
cool. What I wanna do with opend (and hopefully upstream will follow on this too) is basically `core.sys.apple` similar to `core.sys.windows`, with as comprehensive as realistic bindings to the os apis that just work out of the box on all compilers, so users here feel like it is a first class platform.

i'd like to write an auto converter thing (probably based on dstep) to do more but just haven't gotten around to it and what you have here might be a better shared point to start anyway.

**Comment by LunaTheFoxgirl** [comment]
> cool. What I wanna do with opend (and hopefully upstream will follow on this too) is basically `core.sys.apple` similar to `core.sys.windows`, with as comprehensive as realistic bindings to the os apis that just work out of the box on all compilers, so users here feel like it is a first class platform.
> 
> 
> 
> i'd like to write an auto converter thing (probably based on dstep) to do more but just haven't gotten around to it and what you have here might be a better shared point to start anyway.

I frankly think it would be a bad idea to bloat the standard library with that. But it's your project, not mine.

That being said this code is still partially a WIP, so I'll first properly consider changing its license once I have more of foundation covered.

Also auto conversion is often a bad idea since Apple's documentation often has examples that would be better off being rewritten in D for the end user. Far too much of D code has basically little to no documentation, or just poor documentation.

**Comment by adamdruppe** [comment]
Note that if you're porting Apple's documentation examples directly, you'll be bound by their license for the distribution.

But yeah I agree having nice doc examples is good. That's one thing we never got working right in gtkd - the code and documentation itself ported over, but the examples were still in C which was disappointing.

**Comment by LunaTheFoxgirl** [comment]
> Note that if you're porting Apple's documentation examples directly, you'll be bound by their license for the distribution.
> 
> 
> 
> But yeah I agree having nice doc examples is good. That's one thing we never got working right in gtkd - the code and documentation itself ported over, but the examples were still in C which was disappointing.

I'm generally avoiding full on one-to-one translation of examples but instead go for getting the same idea across. So if something is done different in Objective-D that will be represented.

**Comment by LunaTheFoxgirl** [comment]
@adamdruppe license has been changed to BSL as of https://github.com/Inochi2D/objective-d/commit/0817c912fdc98a90a1ad6450fb9a638763d9c0ab

Closing this issue.

If you include my code in OpenD, please make sure to keep the copyright notices within the files.

**Comment by adamdruppe** [comment]
Thanks! This is gonna help make D feel first class on Apple.

**Comment by LunaTheFoxgirl** [comment]
Also please note that some of objective-d will rely on the changes from this PR to DMD's frontend @adamdruppe 
https://github.com/dlang/dmd/pull/20559

Additionally there's a reliance on my LDC PR, which you'd have to integrate as well.
